classes: {
  layer: {
    label.near: outside-top-left
    style.border-radius: 5
  }
  component: {
    shape: package
  }
  zone: {
    shape: stored_data
  }
}

grid-columns: 4

sources: {
  class: layer
  grid-rows: 4
  transactional systems
  ERP
  Logs
  3rd party
}

ingestion: {
  class: layer
  grid-rows: 3
  batch
  real-time
  streaming
}

metadata management: {
  class: layer
  grid-columns: 2
  catalog\: Unity: {
    class: component
    link: https://docs.unitycatalog.io/
  }
}
transformation \& loading: {
  class: layer
  grid-columns: 2
  storage: {
    grid-rows: 3
    class: layer
    open table format\: Apache Iceberg
    open file format\: Apache Parquet
    object storage\: S3 compatible
  }
  compute pipelines: {
    grid-rows: 4
    class: layer

    dataframes\: polars: {
      class: component
      link: https://pola.rs/
    }
    validation\: pydantic: {
      class: component
      link: https://docs.pydantic.dev/latest/
    }
    workflow\: Hamilton: {
      class: component
      link: https://hamilton.dagworks.io/en/latest/
    }
    mapping\: FHIRPath: {
      class: component
      link: https://github.com/beda-software/FHIRPathMappingLanguage
    }
    metrics\: dbt Core: {
      class: component
      link: https://docs.getdbt.com/docs/core/installation-overview
    }
  }
}

data access \& retrieval: {
  class: layer
  grid-rows: 3
  API\: FastAPI: {
    class: component
    link: https://fastapi.tiangolo.com/
  }
  SQL\: DuckDB: {
    class: component
    link: https://duckdb.org/
  }
  FAIR\: DCAT
}
